name: Build and release executable

on:
  push:
    branches:
      - main

jobs:
 

  build:
    runs-on: windows-latest

    permissions:
        contents: write
        
    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Configure Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Compile executable
      run: |
        pyinstaller --noconsole --onefile --name "zarokh" main.py

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
        files: dist/zarokh.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
