name: Build and release executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest

  build:
    needs: test
    runs-on: windows-latest

    permissions:
        contents: write

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Configure Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Compile executable
      run: |
        pyinstaller --noconsole --onefile --name "zarokh" --icon "assets/images/zarokh.ico" --paths src src/zarokh/__main__.py

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: dist/zarokh.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}